# Generated by Django 4.1.7 on 2023-03-25 11:22

from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transcription",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("audio_file", models.FileField(upload_to="audio_files/")),
                ("transcription", models.TextField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("speaker_id", models.CharField(blank=True, max_length=50)),
                ("confidence_score", models.FloatField(null=True)),
            ],
            options={
                "verbose_name": "Transcription",
                "verbose_name_plural": "Transcriptions",
            },
        ),
    ]
