# Generated by Django 4.1.7 on 2023-03-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcriber", "0003_remove_transcription_speaker_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcription",
            name="audio_original_name",
            field=models.TextField(default="name"),
            preserve_default=False,
        ),
    ]
