# Generated by Django 4.1.7 on 2023-03-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcriber", "0004_transcription_audio_original_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transcription",
            name="audio_file",
            field=models.FileField(upload_to="static/audio/transcribed"),
        ),
    ]
