# Generated by Django 4.1.7 on 2023-03-25 16:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_feature_id_alter_subscriptionplan_id_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Feature",
            new_name="SubscriptionPlanFeature",
        ),
    ]
