# Generated by Django 4.1.7 on 2023-03-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_project_id_alter_usage_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="activate_date",
        ),
        migrations.RemoveField(
            model_name="project",
            name="deactivate_date",
        ),
        migrations.RemoveField(
            model_name="project",
            name="status",
        ),
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="project",
            name="title",
            field=models.CharField(
                default="hello", max_length=255, verbose_name="title"
            ),
            preserve_default=False,
        ),
    ]
