# Generated by Django 4.1.7 on 2023-03-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_remove_project_activate_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
