# Generated by Django 4.1.7 on 2023-03-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_project_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="name",
            field=models.CharField(
                default=None,
                help_text="A free-form name for the API key. Need not be unique. 50 characters max.",
                max_length=50,
                unique=True,
            ),
        ),
    ]
