# Generated by Django 4.1.7 on 2023-03-27 23:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_alter_user_managers_user_date_joined_user_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="created",
        ),
    ]
