# Generated by Django 4.1.7 on 2023-03-28 06:31

import apps.users.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_remove_user_created"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("object", apps.users.managers.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
    ]
