# Generated by Django 4.1.7 on 2023-03-28 06:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_alter_user_managers_remove_user_date_joined_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date joined"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_sign_in",
            field=models.DateTimeField(null=True, verbose_name="last sign in"),
        ),
    ]
