# Generated by Django 4.1.7 on 2023-03-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_user_date_joined_user_last_sign_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="is staff"),
        ),
    ]
